import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 20,
  },
  mainHeader: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#1f2937",
  },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    width: "90%",
    marginVertical: 10,
    height: 50,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    color: "#1f2937",
  },
  submitBtn: {
    width: "50%",
    backgroundColor: "#00786F",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    borderRadius: 10,
    shadowColor: "#00786F",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 4,
  },
  text: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  dividerLine: {
    height: 1,
    width: "90%",
    backgroundColor: "#e5e7eb",
    marginVertical: 15,
  },
  filterContainer: {
    flexDirection: "row",
    width: "90%",
    justifyContent: "space-between",
  },
  filterBtn: {
    width: "30%",
    backgroundColor: "#ffffff",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  filterText: {
    color: "#1f2937",
    fontSize: 15,
    fontWeight: "500",
  },
  activeFilterBtn: {
    width: "30%",
    backgroundColor: "#00786F",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#00786F",
  },
  activeFilterText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  todosContainer: {
    marginTop: 20,
    width: "90%",
    maxHeight: "70%",
    marginBottom: 50,
  },
  todoItem: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    padding: 15,
    borderRadius: 8,
    marginVertical: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 1,
  },
  doneTodo: {
    textDecorationLine: "line-through",
    color: "#9ca3af",
  },
});
